### DISCUSSION TITLE
Process lmdb data

### DISCUSSION THREAD

**Discussion by matr1x-1** [mir-group/nequip#502] [Q&A] [answered]
Hello,

I have a question regarding lmdb data: In past versions of NequIP it was possible to do something like this:

```
dataset:
  # graph generated with cutoff radius 6 and max neighbors 50
  - src: datasets/SiN/atom_graph_rmax6.0_maxneighbor50/train.lmdb
    normalize_labels: True
    per_atom: True
    normalize_labels_json: datasets/SiN/atom_graph_rmax6.0_maxneighbor50/normalize_stats.json
  - src: datasets/SiN/atom_graph_rmax6.0_maxneighbor50/valid.lmdb
  - src: datasets/SiN/atom_graph_rmax6.0_maxneighbor50/test.lmdb
```

It seems this way of treating lmdb files is no longer supported. I tried:
```
data:
  _target_: nequip.data.dataset.NequIPLMDBDataset
  file_path: train.lmdb
```
but this gives an assertion error "assert isinstance(datamodule, NequIPDataModule)" from nequip/scripts/train.py (line 97). However, there is no NequIPDataModule class that supports this format.

What is the easiest way to train a new model with the dataset that I have in the lmdb format? The original dataset was in a .xyz format but there was some preprocessing done to limit the number of neighbors to 50. The goal is to reproduce the results from these benchmarks from Neurips 2023: 
- Repo: https://github.com/SAITPublic/MLFF-Framework/tree/main
- Paper: https://proceedings.neurips.cc/paper_files/paper/2023/hash/a1859debfb3b59d094f3504d5ebb6c25-Abstract-Datasets_and_Benchmarks.html

Thank you for your help!

**Comment by Linux-cpp-lisp** [comment, marked as answer]
Hi @matr1x-1 ,

You can directly instantiate `NequIPDataModule` and provide to its, say, `train_dataset` argument an instantiation of of a `NequIPLMDBDataset`. You can see how `ASEDataModule` is really just a thin convenience wrapper around `NequIPDataModule` that helps create the necessary configurations for the individual `ASEDatasets`.  For LMDB, you can just specify these options directly in your config.

However, for a formalized benchmark like this, it is probably most appropriate and easiest to implement a dataset-specific subclass of `NequIPDataModule` that sets up not only the right formats, but also the right splits, etc. You can see some general discussion of PyTorch Lightning DataModules here: https://lightning.ai/docs/pytorch/stable/data/datamodule.html.

> The original dataset was in a .xyz format but there was some preprocessing done to limit the number of neighbors to 50

While of course this may be necessary to reproduce some specific result, we generally strongly recommend against fixed neighbor count limits, and they are not supported by our `nequip.data.transforms.NeighborListTransform`.

**Reply by matr1x-1** [reply]
Thank you very much for your quick response! I will give it a try but considering what you said about strongly recommending against fixed neighbor counts it might be enough to just use the .xyz files then.

**Comment by cw-tan** [comment]
Hi @matr1x-1 

Thank you for your interest! Two comments to add on (which overlaps a bit with @Linux-cpp-lisp's advice)

- In the config file, `data` should refer to a `DataModule`, not a `Dataset` (see https://nequip.readthedocs.io/en/latest/guide/config.html#data). Since we do not expose an `LMDBDataModule` class, you'll have to use the base `NequIPDataModule` class (see https://nequip.readthedocs.io/en/latest/guide/config.html#data), and specify the `xx_dataset` arguments with the `NequIPLMDBDataset` (see https://nequip.readthedocs.io/en/latest/guide/config.html#data).  
- I cannot guarantee that their LMDB format is compatible with the NequIP framework's LMDB format, so this may outright fail. If you really need to limit the number of neighbors to 50, one approach might be to use their `.xyz` file format, which is supported by the NequIP framework through the `ASEDatamodule` (see https://nequip.readthedocs.io/en/latest/api/datamodule.html#nequip.data.datamodule.ASEDataModule), then write a custom data transform to be applied after the neighborlist transform that limits the number of neighbors according to how they did it. Additionally, I think you want to `exclude` stress keys since all structures might not have them, e.g.
```
data:
  _target_: nequip.data.datamodule.ASEDataModule
  # other args
  exclude_keys:
    - stress
```
