### ISSUE TITLE
❓ [QUESTION] Sweeping hyperparemeters with Weights and Biases

### ISSUE THREAD

**Issue by rschireman** [mir-group/nequip#296]
Hi all,

I'm relatively new to the code here, is there a way to use Weights and Biases to sweep hyperparameters (like the batch size, etc.)? I've been using the following code:

```
sweep_id = wandb.sweep(sweep_config, project="sweep")
trainer = TrainerWandB(model=model,**dict(minimal_config))
trainer.save()
trainer.set_dataset(dataset)
wandb.agent(sweep_id, trainer.train(), count=5)
```

and my `sweep_config` looks like this:

```
{'method': 'random',
 'metric': {'goal': 'minimize', 'name': 'validation_e'},
 'parameters': {'batch_size': {'distribution': 'q_log_uniform_values',
                               'max': 256,
                               'min': 32,
                               'q': 8},
                'learning_rate': {'distribution': 'uniform',
                                  'max': 0.1,
                                  'min': 0}}}

```
The first iteration runs fine, but the subsequent runs fail

**Comment by Hongyu-yu** [comment]
Hi @rschireman,
Sure, with some small modification below on the source code, you can sweep hyperparameters.
In `nequip/scripts/train.py` line 25, change the default `run_name="NequIP",` into `run_name="rand_"+str(uuid.uuid4()),` and insert `import uuid` in the first line so that the sweep will generate random `run_name` for the calculations.
You can either change the code in your environment directly or on the source code with `pip install .`.

Then you can create two config file, one for the sweep hyperparameter and one for the basic config file.

For `sweep_config.yaml`, here is an example:
```yaml
project: {your project name}
program: nequip-train
method: random
name: sweep_1
description: sweep over loss coefficients and batch size

# metric:
#   goal: minimize
#   name: validation_f_rmse

command:
  - ${env}
  - ${program}
  - ".../base.yaml" # Absolute path of your basic config yaml file
 
parameters:
  batch_size:
    distribution: int_uniform
    min: 1
    max: 5
  loss_coeffs:
      parameters:
          stress:
              distribution: uniform
              min: 1.0
              max: 10.0
          total_energy:
              value: 
              - 1.
              - PerAtomMSELoss
          forces:
              distribution: uniform
              min: 1
              max: 10
```
Hope it helps!
