### ISSUE TITLE
🐛 [BUG] Cannot run nequip-train with provided example

### ISSUE THREAD

**Issue by Quicken90905** [mir-group/nequip#370]
I tried run the example for a minimal training with energies from [ASEDataset](https://github.com/mir-group/nequip/blob/c56f48fcc9b4018a84e1ed28f762fadd5bc763f1/nequip/data/dataset.py#L808):
```
Example: Given an atomic data stored in "H2.extxyz" that looks like below:

    ```H2.extxyz
    2
    Properties=species:S:1:pos:R:3 energy=-10 user_label=2.0 pbc="F F F"
     H       0.00000000       0.00000000       0.00000000
     H       0.00000000       0.00000000       1.02000000
    ```

    The yaml input should be

    ```
    dataset: ase
    dataset_file_name: H2.extxyz
    ase_args:
      format: extxyz
    include_keys:
      - user_label
    key_mapping:
      user_label: label0
    chemical_symbols:
      - H
    ```
```
But when I run ```nequip-train test.yaml``` (with test.yaml having the provided contents) I get ```runtimeerror: failed to build object with prefix `dataset` using builder `npzdataset```.
