### ISSUE TITLE
MLFF for Silicon

### ISSUE THREAD

**Issue by knc6** [mir-group/nequip#407]
Training a silicon MLFF with nequip shows reasonable force error but high energy MAEs. A colab notebook is kept [here](https://colab.research.google.com/github/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/Train_MLFF_NEQUIP.ipynb) . Any thoughts on what could be going wrong in terms of setting config parameters etc.?

**Comment by cw-tan** [comment]
Hi @knc6,

Thank you for your interest in using NequIP and apologies for the delay! Maybe you've figured it out by now, but it appears that the config file you're using only includes forces in the loss function, i.e. 
```
# loss function
loss_coeffs: forces
```
You can also include energies in the loss function as follows
```
# loss function
loss_coeffs:                                                                        
  forces: 1
  total_energy:                                                                    
    - 1
    - PerAtomMSELoss
```
For example, see [this](https://github.com/mir-group/nequip/blob/main/configs/example.yaml) `example.yaml`.
